//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTweaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinTweaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected devices.
        /// </summary>
        internal static string ConnectedUsbDevicesString {
            get {
                return ResourceManager.GetString("ConnectedUsbDevicesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download speed (MB/s).
        /// </summary>
        internal static string DownloadSpeedString {
            get {
                return ResourceManager.GetString("DownloadSpeedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get entry.
        /// </summary>
        internal static string EntryRetreiveErrorString {
            get {
                return ResourceManager.GetString("EntryRetreiveErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU.
        /// </summary>
        internal static string GraphicsCardString {
            get {
                return ResourceManager.GetString("GraphicsCardString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        internal static string IpAddressString {
            get {
                return ResourceManager.GetString("IpAddressString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor.
        /// </summary>
        internal static string MonitorString {
            get {
                return ResourceManager.GetString("MonitorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motherboard.
        /// </summary>
        internal static string MotherBoardString {
            get {
                return ResourceManager.GetString("MotherBoardString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating System.
        /// </summary>
        internal static string OperatingSystemString {
            get {
                return ResourceManager.GetString("OperatingSystemString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping (ms).
        /// </summary>
        internal static string PingString {
            get {
                return ResourceManager.GetString("PingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU.
        /// </summary>
        internal static string ProcessorString {
            get {
                return ResourceManager.GetString("ProcessorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAM.
        /// </summary>
        internal static string RandomAccessMemoryString {
            get {
                return ResourceManager.GetString("RandomAccessMemoryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to removable devices.
        /// </summary>
        internal static string RemovableUsbDevicesString {
            get {
                return ResourceManager.GetString("RemovableUsbDevicesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        internal static string StorageString {
            get {
                return ResourceManager.GetString("StorageString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System information.
        /// </summary>
        internal static string SystemInformationString {
            get {
                return ResourceManager.GetString("SystemInformationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uptime.
        /// </summary>
        internal static string UptimeString {
            get {
                return ResourceManager.GetString("UptimeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB.
        /// </summary>
        internal static string UsbString {
            get {
                return ResourceManager.GetString("UsbString", resourceCulture);
            }
        }
    }
}
